### ISSUE TITLE
No improvement in performance with WSMP even though multithreading is enabled

### ISSUE THREAD

**Issue by DebasishTapna** [coin-or/Ipopt#11]
Hi There,

I was trying to use WSMP with Ipopt 3.12.8 for performance improvement. But was unable see any performance gain. PFA zip file having ipopt.out files with 1, 4 and 8 threads. Can anybody please have a look?

Thanks,
Debasish

[ipopt.zip](https://github.com/coin-or/Ipopt/files/1351641/ipopt.zip)

**Comment by svigerske** [comment]
The problem is rather small (139 variables and 97 constraints), so I doubt that much speedup can be achieved by parallelizing the solution of the linear system. Further, most time seems to be spend for function evaluation (about 9.6s), and only very little in Ipopt itself (about 0.1s). Part of the time spend for the letter is spend in WSMP, which you try running with multiple threads.
