### ISSUE TITLE
Optimal settings for AMD?

### ISSUE THREAD

**Issue by WJWest** [coin-or/Ipopt#376]
Good day,

I've seen a number of discussions on optimizing code for use with AMD hardware (especially which concerns the use of Intel's MKL):

- [How To Use MKL with AMD Ryzen and Threadripper CPU's](https://www.pugetsystems.com/labs/hpc/How-To-Use-MKL-with-AMD-Ryzen-and-Threadripper-CPU-s-Effectively-for-Python-Numpy-And-Other-Applications-1637/)

- [AMD Threadripper 3970x Compute Performance Linpack and NAMD](https://www.pugetsystems.com/labs/hpc/AMD-Threadripper-3970x-Compute-Performance-Linpack-and-NAMD-1631/)

According to the IPOPT documentation, "**it is highly recommended that you obtain an efficient implementation of the BLAS and LAPACK library, tailored to your hardware**". Which implementations thereof would be considered optimal for AMD hardware? The documentations cites ACML (AMD Core Math Library), but this is now considered end-of-life.

I would really appreciate any feedback on this!

Kind regards

**Comment by svigerske** [comment]
I don't know, but maybe some else do. You might have more luck on the mailing list, though.

I don't have an easy access to an AMD CPU at the moment, but as they become more popular again, this should change over the next years. The links you mention are interesting. I'll replace the mention of ACML by BLIS in the documentation.

**Comment by kkofler** [comment]
Note that BLIS is actually a generic/portable Free / Open Source implementation of BLAS, the [AMD version](https://github.com/amd/blis) is a fork of the [generic official version](https://github.com/flame/blis).

Also note that GotoBLAS (also mentioned in main.dox) is also EOL, but was relicensed under a Free / Open Source license by the copyright holders and forked by the community as [OpenBLAS](https://github.com/xianyi/OpenBLAS). This has replaced ATLAS as the preferred implementation in some GNU/Linux distributions (e.g., Fedora) because it supports runtime CPU detection and because it includes hand-tuned vectorized assembly for many of the detectable CPU families. As a result, the claim in main.dox that the distribution BLAS is usually not optimized is also not necessarily true anymore. (That said, for some bizarre reason, I have found OpenBLAS to actually make Ipopt slower than the unoptimized reference BLAS and LAPACK in my tests. I have so far not been able to figure out why. So, caveat emptor.)

**Comment by svigerske** [comment]
Thank you for the corrections and clarifications. That's very helpful. I've updated the docu accordingly.
