### ISSUE TITLE
Pardiso - Stack Smash detected

### ISSUE THREAD

**Issue by marvin-schl** [coin-or/Ipopt#389]
I compiled Ipopt-3.13 with Pardiso 6 (not mkl version) and Intel MKL. There were no problems when compiling, installing and testing I configured Ipopt with the following Flags:
`../configure --with-lapack="-L${MKLROOT}/lib/intel64 -Wl,--no-as-needed -lmkl_gf_lp64 -lmkl_sequential -lmkl_core -lpthread -lm -ldl -lmkl_lapack95_lp64"  --with-pardiso="-L/usr/local/lib -lpardiso600-GNU800-X86-64 -fopenmp -lgfortran"`

When I try to solve a model which i created with python in pyomo, I get the following error from Ipopt:
`ERROR: Solver (ipopt) returned non-zero return code (-6)
ERROR: Solver log: Ipopt 3.13.3: *** stack smashing detected ***: terminated`
All the other linear solvers work fine.

**Comment by svigerske** [comment]
If I remember right, then Pyomo is writing out a .nl file and then calls the Ipopt executable on that file. Can you save this .nl file and reproduce the problem when running the Ipopt executable by yourself?
Then try to build Ipopt with debug symbols enabled (`--enable-debug` and a `--disable-shared` would also make things easier) and run some debugger or valgrind on it.

I often fear that Ipopt would pick up Pardiso from MKL instead of the Pardiso library while running, since the Pardiso function has the same name in both libs. It would be good to check that first.

Probably it doesn't matter, but I don't think you need `-lmkl_lapack95_lp64`.

**Comment by svigerske** [comment]
Closing as I cannot reproduce this.

**Comment by unartig** [comment]
I was a running into the same problem. For me it was solved by setting the ```--disable-shared``` flag. Thanks @svigerske
