### ISSUE TITLE
need ipopt 32 bit for vs, project or binary,

### ISSUE THREAD

**Issue by wangxue1990** [coin-or/Ipopt#402]
i need the latest version of ipopt 32bit binary,where can i get one or where can i find a vs project,or how to build myself

**Comment by tkralphs** [comment]
The `README` lists several sources for binaries, some of which are 32-bit.

**Comment by wangxue1990** [comment]
> The `README` lists several sources for binaries, some of which are 32-bit.

Thank you for you answer.I have found those: 
1.https://github.com/coin-or/Ipopt/releases
Ipopt-3.13.2-win64-msvs2019-md.zip   (this is 64bit,and ipopt-3.dll file too large,more than 98MB)
2.https://www.coin-or.org/download/binary/Ipopt/
Ipopt-3.11.0-Win32-Win64-dll.7z （not latest）
So is there any way to compile them by MSVisualStudio? I found that the latest version the MSVisualStudio folder has been removed.
Thank you again~

**Comment by svigerske** [comment]
And then there are the ones from https://github.com/JuliaBinaryWrappers/Ipopt_jll.jl/releases, though I'm not sure they are compatible with MSVS, since they were build with GCC.

If you want to try building a current Ipopt by yourself, then instructions can be found [in the documenation](https://coin-or.github.io/Ipopt/INSTALL.html). Nothing has been tested on 32-bit systems, though.
