### ISSUE TITLE
Jacobian and Hessian approximation

### ISSUE THREAD

**Issue by mottelet** [coin-or/Ipopt#409]
Hi, I have two questions:

1-When jacobian_approximation is set to "finite-difference-values", does the approximation take into account the given sparsity pattern sparse_dg (like in Coleman and Moré https://link.springer.com/article/10.1007/BF02612334) ?

2-When hessian_approximation is set to "limited-memory", does the BFGS update operates on full Hessian or is the Hessian pattern sparse_dh taken into account ?

S.

**Comment by svigerske** [comment]
I have never looked into how the Jacobian approximation is computed. It is there, but I don't think that it was meant for regular use.

If the hessian approximation is enabled, then a sparsity pattern for the Hessian is not requested from the user, so that isn't used.
The information about which variables are nonlinear (https://coin-or.github.io/Ipopt/classIpopt_1_1TNLP.html#a9bb5f16cdc2754d1667749268fb1308c) should be used to restrict the Hessian approximation.
