### ISSUE TITLE
Reduced Cost returning unexpected values

### ISSUE THREAD

**Issue by javierlopezfandino** [coin-or/Ipopt#422]
We are using IPOPT in our project and we are finding values of duals associated with the box constraints of the variables having magnitudes really big.

In order to obtain the value of the bound multipliers we are declaring the suffixes ipopt_zL_out and ipopt_zU_out as shown in https://projects.coin-or.org/Ipopt/wiki/IpoptAddFeatures.

Is there any special treatment applied to these suffixes? Any type of rescaling that needs to be done?

Thanks in advance for your help.

**Comment by svigerske** [comment]
As far as I see (https://github.com/coin-or/Ipopt/blob/master/src/Apps/AmplSolver/AmplTNLP.cpp#L758), these are just copied directly from the solution that Ipopt delivers. They should correspond to your problem without extra scaling.

Probably the optimal value in your problem is just very sensible to the variable bounds.
