### ISSUE TITLE
Error when solving a program using an AMD processor

### ISSUE THREAD

**Issue by SlowLearner22** [coin-or/Ipopt#426]
I have recently started using a computer with Windows 10 SO and a AMD RYZEN 9 3950X (AM 4) processor. I have run a pyomo program which uses ipopt as solver which returns an error: 

```
ERROR: Solver (ipopt) returned non-zero return code (3221225501)
ERROR: See the solver log above for diagnostic information.
Traceback (most recent call last):
```

This seems to happen with any optimization code which uses ipopt as a solver; I think that the processor is the issue since I have run the same code without issues in Intel computers. I have downloaded [BLIS](https://anaconda.org/conda-forge/blis), [BLAS](https://anaconda.org/conda-forge/blas), [pyomo](https://anaconda.org/conda-forge/pyomo) and [ipopt](https://anaconda.org/conda-forge/ipopt) from conda forge, since according to [this post](https://community.amd.com/thread/253008), it should fix what is happening to me, but it has been to no effect, the error remains. 

Please, bear in mind that I am a engineering student and not a computer scientist

**Comment by svigerske** [comment]
I don't really see how that post is relevant for a crash on AMD CPUs.

The Ipopt build you say you use seems to have been generated using recipes from https://github.com/conda-forge/ipopt-feedstock. If you can generate something that makes this reproducible (e.g., an .nl file), then they might be able to help. But since they provide Linux and macOS binaries, but you run Windows (its WSL in Windows, I assume), that may not be so easy.
