### ISSUE TITLE
Difference in the number of iterations when running IPOPT on two different machines

### ISSUE THREAD

**Issue by abhyshr** [coin-or/Ipopt#437]
[newell_ipopt_pbpol.log](https://github.com/coin-or/Ipopt/files/5858271/newell_ipopt_pbpol.log)
[marianas_ipopt_pbpol.log](https://github.com/coin-or/Ipopt/files/5858273/marianas_ipopt_pbpol.log)

We are seeing a difference in the number of iterations when running IPOPT on two different machines. The above two logs are for running an optimal power flow application on Newell (Power9 cpu) and Marianas (Intel Xeon E5 cpu). On Newell, it takes 214 iterations, while on Marianas it takes 222 iterations. The same options for the application and IPOPT are being used so we are puzzled by this difference in the number of iterations. Could you help us to shed light on what could be causing this discrepancy?

**Comment by svigerske** [comment]
Different CPUs can give different results on floating-point operations because results of arithmetic operations have to be rounded to fit into the used floating-point format (double precision). Internally, the CPU may use a higher precision (80bit vs 64bit) for a number of operations before putting the result back into memory, but it then depends on the CPU architecture and maybe various other circumstances what result one gets at the end. Here, you even seem to use CPUs from two different vendors. If you diff your logs, you see that difference start to be small but then grow from iteration to iteration. You can call yourself lucky that the final number of iterations is still so similar.

Also, I doubt that you could use the same binary on Power and Xeon CPUs, so different compiler versions can also play a role. 
There are compiler flags (intel: -fp-model) that one can use to reduce (maybe even eliminate) the issue from getting different results on different CPUs. I'm not sure that this would also extend to completely different CPU instruction sets (power vs x86_64).
