### ISSUE TITLE
Access curr_grad_f, curr_grad_lag_x, curr_grad_lag_s, curr_exact_hessian in Ipopt::TNLP::intermediate_callback

### ISSUE THREAD

**Issue by g-braeunlich** [coin-or/Ipopt#451]
Hello
From the [docs](https://coin-or.github.io/Ipopt/classIpopt_1_1TNLP.html#a2f962a4c43464adb7928771af84503d6)
I understand, that I cannot directly use the return values given by the `IpoptCalculatedQuantities::curr_*` functions.
I first have to use some `Resort*` functions of an adapter.
What would be the `Resort*` functions corresponding to `curr_grad_*` and `curr_exact_hessian`?

**Comment by svigerske** [comment]
For gradients, `ResortX` should apply, but for entries that correspond to fixed variables, you will get the value of the variable instead of 0.
For the Hessian, I don't think that there is any function.

But what happens [in `ResortX`](https://github.com/coin-or/Ipopt/blob/master/src/Interfaces/IpTNLPAdapter.cpp#L2362) isn't that complicated:  So [`P_x_full_x_`](https://github.com/coin-or/Ipopt/blob/master/src/Interfaces/IpTNLPAdapter.hpp#L447) is a permutation matrix that stores the mapping between indices in your TNLP and the NLP that you Ipopt works with internally. Unfortunately, it is private at the moment - fortunately you can just change code. There also seems to be a `h_idx_map_` that could be useful.

**Comment by svigerske** [comment]
Ipopt 3.14 has some functions added to `TNLP` that allow to request the current iterate and various violations during intermediate_callback (or finalize_solution).
This gives access to the absolute values in `curr_grad_lag_x`.
`curr_grad_lag_s` should correspond to dual values of the constraints, so they should also be available.

I don't think I want to do anything to return the objective gradient or Hessian back to the user.
