### ISSUE TITLE
Incorrect/inaccurate duals of binding constraints

### ISSUE THREAD

**Issue by zjamaludin** [coin-or/Ipopt#468]
Hello! First of all, thank you for this awesome solver!

I use IPOPTH via GAMS to solve AC Optimal Power Flow model (NLP). I also extract the duals (i.e. marginals) of the solutions for other analyses. I observed that the incorrect/inaccurate duals of the binding inequality constraints were returned by IPOPTH for some simple test cases in which the expected duals have been pre-defined. I would like to note here that the expected values were successfully returned by other nonlinear solvers (e.g. SNOPT and CONOPT), and also from the linearized version of the NLP model (solved using CBC and CLPEX).

However, the correct IPOPTH duals can be obtained when the complementarity infeasibility tolerance (`compl_inf_tol`) is set to `1E-14` (instead of the default `1E-4`); even though the primal solutions from both tolerances are fairly the same, but with slightly improved objective value than that of the default setting. Such tight tolerance obviously increases the number of iteration and solution time to reach optimality, especially when the model is scaled to solve, for example, 100k variables. Q: What is the reason behind this? Is there any recommendations to obtain the correct/accurate duals without extremely tightening the `compl_inf_tol`?

**Comment by svigerske** [comment]
I don't know what motivated the defaults for Ipopt tolerances.
I guess the idea is that `tol` is the main tolerance that Ipopt works with. This tolerance controls the allowed violations in primal and dual feasibility and complementarity of the scaled problem, which is the problem that Ipopt works with internally.   
The tolerances `dual_inf_tol`, `compl_inf_tol`, and `constr_viol_tol` control violations in the unscaled problem. They are there to control how much the violations can increase when unscaling. However, it can be difficult for Ipopt to satisfy tiny tolerances on violations in the unscaled problem if violations are already small in the scaled problem. That might be the reason why these tolerances are set to rather large values by default.

It could be that the more accurate duals of SNOPT, CONOPT, CLP, and CPLEX have something to do with these solvers running some sort of active-set algorithm by default, while Ipopt is doing interior point. For the latter, complementarity is relaxed by design (slack*dual = mu), while it isn't for the former.   
I would hope that you could obtain better duals also with higher values for compl_inf_tol than 1e-14.

**Comment by zjamaludin** [comment]
Hi Stefan,
Thank you for your feedback. I will continue to explore other Ipopt options that might help to return the accurate duals without extremely tightening the `compl_inf_tol`. Good point on scaling - I do scale my model as part of problem formulation, and will explore some reformulation approaches too.

Zamry
