### ISSUE TITLE
Spral with Windows

### ISSUE THREAD

**Issue by jaharris85** [coin-or/Ipopt#496]
Hi,

Has anyone else managed to successfully compile and use Spral with MSVC?

I can only compile Spral with OpenMP disabled and even then the HS071 example throws an exception on the first call to spral_ssids_analyse_ptr32 (line 488 of IpSpralSolverInterface.cpp).

Thanks.

**Comment by svigerske** [comment]
I didn't try Windows so far (or I tried short on appveyor and gave up quickly).

Which version of SPRAL is this?

**Comment by jaharris85** [comment]
I had to use the current master branch because of some issues compiling the latest released version from 2016.

**Comment by svigerske** [comment]
The last I tried that worked for me on Linux is ralna/spral@c8c3fcdba5c6e1120a642425f774510055950f44. But travis jobs on mac and linux also used the latest master until some weeks ago (when travis stopped working).

I would first make sure that you have a version that works on Linux and then use the exact same one on Windows. If that crashes, then debug that.

Since you said you had to disable OpenMP, I wondered whether you may be on an old version where issues with OpenMP and recent GCC wasn't fixed yet. There was another fix around the same time in ralna/spral that required a change in the Ipopt/Spral interface to work again.

**Comment by jaharris85** [comment]
I needed to disable OpenMP because MSVC only supports OpenMP 2.0.

Even building from the commit you suggested I still hit the same exception when calling the Page destructor in BuddyAllocator.hxx:
      if(next_ && head_[nlevel-1] != 0)
         throw std::runtime_error("outstanding allocations on cleanup\n");
with head_ containing the entries {-1, -1, -1, -1, -1, -1, 64, 128, 256, 512, 1024, 2048, 4096, 8192, 16384, -1}.

Removing this exception we get printed:
    Error return from ssids_factor. Error flag =  -1
    In SpralSolverInterface::Factorization: Unhandled error. info.flag = -1.

When compiling the C++ components of Spral I get several warnings about conversion from size_t to int, but otherwise no issues.

**Comment by svigerske** [comment]
I see. That looks like it is something to check with the Spral developers.

**Comment by jaharris85** [comment]
Thanks for your help. I will ask them.
