### ISSUE TITLE
Talk on IPOPT

### ISSUE THREAD

**Issue by bharswami** [coin-or/Ipopt#534]
I am doing my PhD in Aerospace Engineering from the Indian Institute of Technology Madras. I am not much familiar with the math behind IPOPT but have used it extensively and know that it is quite powerful. To the best of my knowledge, there are also several other users of IPOPT in my institute. It will be helpful for us if we get an in-depth understanding of the algorithm behind the solver - it will aid us in our work. Would you be willing to spare time to share your expertise in the same by giving a talk for us?

**Comment by svigerske** [comment]
I'm closing this, since Andreas didn't answer here for a month. He's the one with the "in-depth understanding of the algorithm". If he hasn't replied to you via other channels, then I guess that means that he won't have the time to give a talk, sorry. The [implementation paper](http://www.optimization-online.org/DB_HTML/2004/03/836.html) is usually a good starting point to get a better understanding of what is happening in Ipopt.

**Comment by bharswami** [comment]
I haven't personally contacted him. Can I have his email address?

**Comment by svigerske** [comment]
https://www.mccormick.northwestern.edu/research-faculty/directory/profiles/waechter-andreas.html

**Comment by andrea5w** [comment]
Hi, Sorry I missed this. 

Unfortunately, we don’t have the time to give presentations like this. There is a tutorial paper that might be helpful. 

Regards,

Andreas
