### ISSUE TITLE
Internal order of the constraint multipliers

### ISSUE THREAD

**Issue by StevenvanLeeuwen** [coin-or/Ipopt#556]
### Discussed in https://github.com/coin-or/Ipopt/discussions/502
The reply tells us that a nonzero multiplier value for `g(x) - s = 0` means one of these two are active: `g(x) <= rhs` or `lhs <= g(x)`. However this assumes that one of these two are active: `lhs <= s` or `rhs <= s`. Why does this have to be the case? In fact,
why are the bounds constraint multipliers on `s` not available in any of the Ipopt interfaces, such as TNLPAdapter, or included in the Ipopt Algorithm description?

<div type='discussions-op-text'>

<sup>Originally posted by **309815765** August  3, 2021</sup>
Hi,

I need to get the constraint multipliers for sensitivity analysis. To my knowledge, the constraint with both lower bound and upper bound will be converted to two constraints (correct me if it's wrong). I'd like to know how does Ipopt order multipliers (lambda) for constraints, especially for the constraints with both boundaries.

Thanks</div>

**Comment by svigerske** [comment]
In a feasible solution, you have `g(x) = s`, so if `lhs <= g(x) <= rhs` is active, then so is also `lhs <= s <= rhs`.
If `g(x) = s` is violated, then indeed it is possible you get zero multipliers on `lhs <= g(x) <= rhs`, even when they are active.   
But optimality conditions only need to hold in optimal (and thus feasible) solutions.

One purpose of TNLPAdapter is to give an interface for a formulation with `lhs <= g(x) <= rhs` and do the reformulation with slack variables automatically. Since this should be invisible to a user, it also does not expose the introduced slack variables prominently. One can access a lot of information in terms of the internal NLP formulation from the `IpData` and `IpCalculatedQuantities` objects that are accessible in the TNLP. However, using these isn't really trivial, e.g., because slack variables are only introduced if `lhs != rhs`.     
Alternatively, it should be possible to skip over the reformulation from `TNLPAdapter` and specify your problem in the form that Ipopt uses internally, i.e., by deriving from NLP (https://coin-or.github.io/Ipopt/classIpopt_1_1NLP.html#details) instead of TNLP.
