### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by didibaba** [coin-or/Ipopt#579]
Hi dear,

Currently, I was compiling the code on Ubuntu 20.04 and got the error '../../../../../Ipopt/src/Algorithm/LinearSolvers/IpMumpsSolverInterface.cpp:22:10: fatal error: mpi.h: No such file or directory'.
I have tried install libopenmpi-dev, but no working.
It would be appreciated if someone could help.

P.S. Fortran I used was installed by `apt install gfortran`.

**Comment by svigerske** [comment]
If you build Mumps via [https://github.com/coin-or-tools/ThirdParty-Mumps/](ThirdParty-Mumps), then it shouldn't try to include `mpi.h`. It should include `mumps_mpi.h` instead:

https://github.com/coin-or/Ipopt/blob/f28ee288dbf253cde184ac13ef21da64f44e00bf/src/Algorithm/LinearSolvers/IpMumpsSolverInterface.cpp#L25-L29

If you have another installation of Mumps, then check whether you need to add some flags to your `--with-mumps-cflags` arg of configure to tell the compiler where to find your `mpi.h`.

**Comment by didibaba** [comment]
@svigerske The command I used to build Mumps was
```bash
./get.Mumps
./configure --prefix=/usr/local/ipopt
make install
```
with the mpi.h not found error.

Currently, I temporarily solved the problem by installing libopenmpi-dev, and add include searching path at `/usr/lib/aarch64-linux-gnu/openmpi/include`.

I am not quite sure if this is the correct solution.

**Comment by svigerske** [comment]
The logic is that ThirdParty-Mumps installs a `/usr/local/ipopt/include/coin-or/mumps/mumps_compat.h` which contains the line
```c
#define COIN_USE_MUMPS_MPI_H
```
This tells Ipopt that it should include `mumps_mpi.h` instead of `mpi.h`.

You might want to check that the `mumps_compat.h` header is correctly installed and that the Ipopt build is indeed using this when building the Mumps interface. If there is another Mumps installation, there could also be conflicts.

**Comment by kashifzr** [comment]
@svigerske  I did install third party Mumps but when I install Ipopt with ../configure --with-mumps-cflags then it works but make still create missing mpi.h header file error.  Even ../configure command in build folder works without --with-mumps-cflags 

How to install mumps inside Ipopt when i run ./get.Mumps in ThirdParty-Mumps then it fail to connect to repository to download. Other packages like ASL, HSL, METIS,  BLAS is easily download with ./get.XXX commands

**Comment by svigerske** [comment]
> @svigerske I did install third party Mumps but when I install Ipopt with ../configure --with-mumps-cflags then it works but make still create missing mpi.h header file error. Even ../configure command in build folder works without --with-mumps-cflags

Maybe you didn't specify all header file directories that are necessary with your value of `--with-mumps-cflags`.

> How to install mumps inside Ipopt when i run ./get.Mumps in ThirdParty-Mumps then it fail to connect to repository to download. Other packages like ASL, HSL, METIS, BLAS is easily download with ./get.XXX commands

This sounds like you try to install some old version of Ipopt, since ThirdParty-Metis and ThirdParty-Blas have been retired.
Please try with a current Ipopt version (3.14.14). Otherwise, download the source manually and follow the steps in `get.Mumps` manually to provide the `MUMPS` directory in `ThirdParty-Metis`.

**Comment by kashifzr** [comment]
@svigerske thanks Now Its works by following Normal procedure
