### ISSUE TITLE
nnz_jac_g and nnz_h_lag

### ISSUE THREAD

**Issue by matheusdiogenesandrade** [coin-or/Ipopt#688]
Hello.

Folks! I am writing a C++ Ipopt model for the [Quadratic Assignment Problem](https://doi.org/10.1016/j.ejor.2005.09.032) (QAP), and I am in doubt with two parameters: `nnz_jac_g` and `nnz_h_lag`. How do I find the value of these two parameters?

Thanks and regards.

**Comment by svigerske** [comment]
There is documentation on the C++ interface in https://coin-or.github.io/Ipopt/INTERFACES.html#INTERFACE_CPP.

`nnz_jac_g` essentially counts all appearances of variables in all constraints. For a QAP, where you have only linear constraints, this should be the number of nonzero coefficients in your constraint matrix.

`nnz_h_lag` is the number of nonzero entries in the Hessian of the Lagrangian. Since you have only linear constraints and a quadratic objective function, this is the number of nonzeros in the quadratic coefficients matrix. Here, assume it is a symmetric matrix and count only the nonzeros in the lower-left triangle.

Note that Ipopt can only find locally optimal solutions to continuous nonlinear programs (no binary variables).

**Comment by matheusdiogenesandrade** [comment]
Thank you very much.
