### ISSUE TITLE
IPOPT restoration phase error

### ISSUE THREAD

**Issue by bharswami** [coin-or/Ipopt#713]
Why would this error be thrown in IPOPT?
Cannot call restoration phase at point that is almost feasible (violation 0.000000e+00). Abort in line search due to no other fall back.

**Comment by svigerske** [comment]
Would need to look into what happened before that message.
It is caused by the linesearch to fail. One thing Ipopt would then try is to go into feasible restoration phase and hope things will do better there. However, restoration phase cannot be called at feasible points (there is no feasibility to restore), so it is out of options and aborts.
