### ISSUE TITLE
MA28TDependencyChecker is referenced but not built

### ISSUE THREAD

**Issue by rlkamalapurkar** [coin-or/Ipopt#783]
Setup (I want statically linked ipopt):
- Sources (taken from the Ipopt, ThirdParty-Mumps, and ThirdParty-HSL repos) in `$DIR/Ipopt`, `$DIR/mumps`, and `$DIR/hsl`. 
- HSL includes all Maxx solvers
- The file libopenblas.a is copied to `$DIR/install/lib`

Build static MUMPS using
```
export PREFIX=$DIR/install
export LIBDIR=$PREFIX/lib
cd $DIR/mumps/build
../configure --prefix="$PREFIX" --with-lapack-lflags="-Wl,--no-as-needed $LIBDIR/libopenblas.a -lm' --disable-shared
make
make install
```
static HSL using
```
cd $DIR/hsl/build
../configure --prefix="$PREFIX" --with-lapack-lflags="-Wl,--no-as-needed $LIBDIR/libopenblas.a -lm' --disable-shared
make
make install
```
and static Ipopt using
```
cd $DIR/Ipopt/build
export INCLUDEDIR=$PREFIX/include/coin-or
../configure --prefix="$PREFIX" --with-lapack-lflags="-Wl,--no-as-needed $LIBDIR/libopenblas.a -lm" --with-mumps-cflags="-I$INCLUDEDIR/mumps" --with-mumps-lflags="-L$LIBDIR/libcoinmumps.a" --with-hsl-cflags="-I$INCLUDEDIR/hsl" --with-hsl-lflags="-Wl,$DIR/install/lib/libcoinhsl.a -lgfortran -lm" --disable-shared
```
I then try to build hs071_cpp using the following modifications to the default Makefile
```
# Include directories
INCL = -I${prefix}/include/coin-or  -I${prefix}/include/coin-or/hsl -I${prefix}/include/coin-or/mumps  -DIPOPTLIB_BUILD $(ADDINCFLAGS)

# Linker flags
LIBS = -L${exec_prefix}/lib -lipopt ${prefix}/lib/libcoinhsl.a -lgfortran -lm ${prefix}/lib/libcoinmumps.a -lmetis ${prefix}/lib/libopenblas.a -ldl

```
to get 
```
IpTNLPAdapter.cpp:(.text+0x72f1): undefined reference to `Ipopt::Ma28TDependencyDetector::Ma28TDependencyDetector()'
```

If I go into IpTNLPAdapter.cpp and comment out all the code that references Ma28, then everything works as expected.

**Comment by svigerske** [comment]
It seems that the `CoinHslConfig.h` header, which is build and installed by ThirdParty-HSL, says that MA28 is available, but the check for MA28 in the HSL library during Ipopt's configure is failing. The latter decides whether to build Ma28TDependencyDetector.
Please check the config.log from Ipopt why it failed to find the `ma28ad` symbol (failing on `ma28a` (the single-precision variant of `ma28ad` is ok)). Maybe your `--with-hsl-lflags` need to be adjusted.

Also, it should be sufficient to use
```
../configure --prefix="$PREFIX" --with-lapack-lflags="-Wl,--no-as-needed $LIBDIR/libopenblas.a -lm" --disable-shared
```
to configure Ipopt. It should pick up mumps and hsl automatically via pkg-config, since they are installed in the same `$PREFIX`.
